import { Material } from '../types';

export const sampleMaterials: Material[] = [
  {
    id: 'sample-1',
    materialId: 'ADN-2024-00001',
    title: 'Introduction to Algebra',
    description: 'A comprehensive learning module covering basic algebraic concepts including variables, equations, and functions for Grade 7 students.',
    type: 'ppt',
    status: 'completed',
    developerName: 'Maria Santos',
    developerEmail: 'maria.santos@deped.gov.ph',
    contactNumber: '0917-123-4567',
    school: 'Manila Science High School',
    district: 'District I',
    fileName: 'Algebra_Intro_Grade7.pptx',
    fileUrl: '#',
    uploadedAt: new Date('2024-01-15'),
    category: 'Mathematics',
    qaRemark: {
      result: 'passed',
      comments: 'Excellent material. Well-structured content with clear examples.',
      reviewedAt: new Date('2024-01-17'),
      reviewedBy: 'Admin User',
    },
  },
  {
    id: 'sample-2',
    materialId: 'ADN-2024-00002',
    title: 'Photosynthesis and Plant Biology',
    description: 'Interactive presentation explaining the process of photosynthesis, including diagrams and animations for better understanding.',
    type: 'pdf',
    status: 'ongoing',
    developerName: 'Juan Reyes',
    developerEmail: 'juan.reyes@deped.gov.ph',
    contactNumber: '0928-234-5678',
    school: 'Quezon City Science High School',
    district: 'District II',
    fileName: 'Photosynthesis_Module.pdf',
    fileUrl: '#',
    uploadedAt: new Date('2024-01-20'),
    category: 'Science',
  },
  {
    id: 'sample-3',
    materialId: 'ADN-2024-00003',
    title: 'English Grammar Basics',
    description: 'A detailed guide on English grammar fundamentals including parts of speech, sentence structure, and common writing mistakes.',
    type: 'pdf',
    status: 'pending',
    developerName: 'Ana Cruz',
    developerEmail: 'ana.cruz@deped.gov.ph',
    contactNumber: '0939-345-6789',
    school: 'Rizal High School',
    district: 'District III',
    fileName: 'English_Grammar_Guide.pdf',
    fileUrl: '#',
    uploadedAt: new Date('2024-01-22'),
    category: 'English',
  },
  {
    id: 'sample-4',
    materialId: 'ADN-2024-00004',
    title: 'Filipino Panitikan Quiz Game',
    description: 'An interactive quiz game covering Filipino literature from different periods, designed for Grade 9-10 students.',
    type: 'game',
    status: 'pending',
    developerName: 'Pedro Garcia',
    developerEmail: 'pedro.garcia@deped.gov.ph',
    contactNumber: '0940-456-7890',
    school: 'Pasig City Science High School',
    district: 'District IV',
    linkUrl: 'https://example.com/filipino-quiz-game',
    uploadedAt: new Date('2024-01-23'),
    category: 'Filipino',
    pendingReview: true,
  },
  {
    id: 'sample-5',
    materialId: 'ADN-2024-00005',
    title: 'Geography Interactive Map',
    description: 'Interactive website featuring Philippine geography with clickable regions showing provinces, cities, and key landmarks.',
    type: 'website',
    status: 'completed',
    developerName: 'Sofia Mendoza',
    developerEmail: 'sofia.mendoza@deped.gov.ph',
    contactNumber: '0951-567-8901',
    school: 'Makati Science High School',
    district: 'District V',
    linkUrl: 'https://example.com/ph-geography-map',
    uploadedAt: new Date('2024-01-10'),
    category: 'Araling Panlipunan',
    qaRemark: {
      result: 'passed',
      comments: 'Very interactive and informative. Great for student engagement.',
      reviewedAt: new Date('2024-01-12'),
      reviewedBy: 'Admin User',
    },
  },
  {
    id: 'sample-6',
    materialId: 'ADN-2024-00006',
    title: 'Physical Education Activity Cards',
    description: 'A set of activity cards with illustrations for different physical exercises suitable for all grade levels.',
    type: 'image',
    status: 'ongoing',
    developerName: 'Carlos Villanueva',
    developerEmail: 'carlos.v@deped.gov.ph',
    contactNumber: '0962-678-9012',
    school: 'Taguig Science High School',
    district: 'District VI',
    fileName: 'PE_Activity_Cards.zip',
    fileUrl: '#',
    uploadedAt: new Date('2024-01-25'),
    category: 'MAPEH',
  },
  {
    id: 'sample-7',
    materialId: 'ADN-2024-00007',
    title: 'Values Education Storybook',
    description: 'Digital storybook with moral lessons and interactive questions for elementary students.',
    type: 'pdf',
    status: 'pending',
    developerName: 'Elena Torres',
    developerEmail: 'elena.torres@deped.gov.ph',
    contactNumber: '0973-789-0123',
    school: 'Manila Science High School',
    district: 'District I',
    fileName: 'Values_Storybook.pdf',
    fileUrl: '#',
    uploadedAt: new Date('2024-01-26'),
    category: 'Edukasyon sa Pagpapakatao',
  },
  {
    id: 'sample-8',
    materialId: 'ADN-2024-00008',
    title: 'Computer Basics Tutorial',
    description: 'Video tutorial series covering basic computer operations, file management, and internet safety.',
    type: 'video',
    status: 'completed',
    developerName: 'Mark Anthony Lim',
    developerEmail: 'mark.lim@deped.gov.ph',
    contactNumber: '0984-890-1234',
    school: 'Quezon City Science High School',
    district: 'District II',
    linkUrl: 'https://example.com/computer-basics',
    uploadedAt: new Date('2024-01-08'),
    category: 'Computer Education',
    qaRemark: {
      result: 'passed',
      comments: 'Clear instructions and well-paced tutorials. Approved for use.',
      reviewedAt: new Date('2024-01-10'),
      reviewedBy: 'Admin User',
    },
  },
];